# Generated by Django 4.1.2 on 2022-11-17 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_invoice_name_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 0, 11, 6, 485024)),
        ),
    ]
