# Generated by Django 4.1.2 on 2022-11-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='size',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productdetail'),
        ),
    ]
