# Generated by Django 4.1.2 on 2022-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_invoicedetail_size_invoicedetail_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
