# Generated by Django 4.1.2 on 2022-11-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='product',
            new_name='product_detail',
        ),
    ]
