# Generated by Django 4.1.2 on 2022-11-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_product_invoicedetail_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
    ]
