# Generated by Django 4.1.2 on 2022-11-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_addressdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', '4'), ('success', '1'), ('wait', '0'), ('return', '2'), ('revoke', '3')], default='booked', max_length=10)),
                ('date', models.DateTimeField(default='')),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.invoice')),
            ],
        ),
    ]
